"""Declarative base for every ORM model.

ARCHITECTURAL DECISION -- an explicit constraint naming convention.

Left to itself, PostgreSQL invents names for constraints and indexes. Those
names end up baked into migration files, and they differ between a database
built by `create_all` and one built by migrations. The consequence appears
months later, when someone writes a migration that drops an unnamed constraint
and Alembic emits `DROP CONSTRAINT ck_orders_...` against a database where the
server called it something else. The migration passes in staging and fails in
production.

Fixing the convention up front makes every constraint name deterministic and
derivable from its columns, so autogenerated migrations are stable and
downgrades actually work. This costs one dictionary now and prevents a class of
migration failure that is genuinely unpleasant to debug under pressure.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# %(table_name)s, %(column_0_N_name)s and friends are SQLAlchemy naming tokens.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_name)s",  # index
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",  # unique constraint
    "ck": "ck_%(table_name)s_%(constraint_name)s",  # check constraint
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",  # primary key
}


class Base(DeclarativeBase):
    """Common declarative base.

    Every model inherits from this class, which means `Base.metadata` is the
    single, complete description of the schema. Alembic reads exactly that
    object to diff the code against the live database, so a model that forgets
    to inherit from `Base` is silently invisible to migrations.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
